# make sure you define tag index before defining tag coordinates
apriltags: [3, 2, 7, 4]

# the program will look for the tag index first to read each tag coordinate
tag3: [0.81, 7.0, 1.2]
tag2: [1.96, 7.0, 1.2]
tag7: [3.11, 7.0, 1.2]
tag4: [4.26, 7.0, 1.2]

# complimentary filter gain. Higher value slower update, less noisy
alpha: 0.95 #0.94

#   linear.x  (+)      Translate forward
#             (-)      Translate backward
#   linear.y  (+)      Translate to left -> (NEGATIVE gain)
#             (-)      Translate to right
#   linear.z  (+)      Ascend
#             (-)      Descend
#   angular.z (+)      Rotate counter clockwise -> (NEGATIVE gain)
#             (-)      Rotate clockwise


#pid_gains: [
#  0.07, 0.010, 0.0,
#  0.07, 0.010, 0.0,
#  0.07, 0.010, 0.0,
#  0.08, 0.010, 0.0
#]0.000625
controller: "lqr"

pid_gains: [
  0.075, -0.001, -0.0003,
  0.075, 0.00075, -0.0001,
  0.085, -0.001, -0.0001,
  0.08, -0.002, 0.0
]

lqr_gains: [
  0.065, 0.0, 0.0, 0.0, 0.0016, 0.0, 0.0, 0.0,
  0.0, 0.065, 0.0, 0.0, 0.0, 0.0016, 0.0, 0.0,
  0.0, 0.0, 0.085, 0.0, 0.0, 0.0, 0.001, 0.0,
  0.0, 0.0, 0.0, 0.060, 0.0, 0.0, 0.0, 0.003,
  0.0, 0.0, 0.0, 0.0, 0.0016, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0016, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.003
]

# set the control loop duration default 30 Hz -> 0.03
dt: 0.03
# set hovering region
goal_thres: 0.6

# trajectory param
#max_vel: 2
#max_acc: 3
max_vel: 1.1
max_acc: 1
