# make sure you define tag index before defining tag coordinates
apriltags: [3, 2, 7, 4]

# the program will look for the tag index first to read each tag coordinate
tag3: [0.81, 7.0, 1.2]
tag2: [1.96, 7.0, 1.2]
tag7: [3.11, 7.0, 1.2]
tag4: [4.26, 7.0, 1.2]

# complimentary filter gain. Higher value slower update, less noisy
alpha: 0.95

#   linear.x  (+)      Translate forward
#             (-)      Translate backward
#   linear.y  (+)      Translate to left -> (NEGATIVE gain)
#             (-)      Translate to right
#   linear.z  (+)      Ascend
#             (-)      Descend
#   angular.z (+)      Rotate counter clockwise -> (NEGATIVE gain)
#             (-)      Rotate clockwise


#pid_gains: [
#  0.07, 0.010, 0.0,
#  0.07, 0.010, 0.0,
#  0.07, 0.010, 0.0,
#  0.08, 0.010, 0.0
#]0.000625

pid_gains: [
  0.07, 0.002, 0.000625,
  0.07, 0.002, 0.000625,
  0.07, 0.002, 0.000625,
  0.08, 0.002, 0.000625
]

# set the control loop duration default 30 Hz -> 0.03
dt: 0.03
# set hovering region
goal_thres: 0.35

# trajectory param
#max_vel: 2
#max_acc: 3
max_vel: 1.1
max_acc: 1
